### ISSUE TITLE
PiHole on custom port

### ISSUE THREAD

**Issue by tscibilia** [WaLLy3K/Pi-hole-Block-Page#12]
I saw you were troubleshooting a ticket using a custom port instead of port 80. I would like to do the same with my install of pihole. however once i change it on the lighttpd.conf file i loose the custom blocked webpage you setup. If i set it back to port 80, it works as expected. 

Is there any additional settings i would need to modify to get the block page to recognize the custom port number being used?

**Comment by WaLLy3K** [comment]
When looking at Issue #7, I had added the code necessary for PHBP to work correctly with different ports. I eventually decided against releasing this, [because Pi-hole will only support port 80](https://github.com/pi-hole/pi-hole/issues/1328) due to how the [`--address`](http://www.thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html) option within `dnsmasq` works. (I.E: Blacklisted sites will always be redirected back to port 80)

If there's a use case scenario where having the port would make PHBP work correctly (on par with the default block page), *and* where Pi-hole still works completely as expected, I'd be more than happy to add in the tiny bit of code needed!

**Comment by tscibilia** [comment]
It's not critical to me, i have alot of different vm running (pihole being one of them) I've made it my practice to change all default ports to some obscure high numbered port (especially for those application i have access to remotely). 

If pi-hole and the block page permitted a different port I would take advantage of that, but it seems like that's not going to be the case.

**Comment by WaLLy3K** [comment]
Ah, that's fair enough! Sorry I couldn't be of more help though.

If someone does discover how to make Pi-hole consistently work (including after a `pihole -up` update) on a non-standard port, feel free to reply to this ticket and I'll be more than happy to do what's needed to make PHBP work!

**Comment by ghost** [comment]
`If someone does discover how to make Pi-hole consistently work (including after a pihole -up update) on a non-standard port`
I managed to have the /admin/ work with https on a non-standard port that works even after an update. I will soon make a pull request on this. I take time because I am also working on creation of a pem certificate during installation or change of https admin port, where the created here pem is of a "very high quality".
