### ISSUE TITLE
Bing.com not working for me in OS X 10.12.2

### ISSUE THREAD

**Issue by AtomicLight** [WaLLy3K/Pi-hole-Block-Page#2]
Using Safari, when I go to BING.com, I get the attached error. But if I use Chrome..I can go there? 

I did whitelist it in PiHole...so I am confused.

Thx

![blocked](https://cloud.githubusercontent.com/assets/25261132/22172505/67dbcb8a-df5d-11e6-8bab-80cb7da8ad35.jpeg)

**Comment by WaLLy3K** [comment]
Sorry that the page has caused you confusion! It's important that you flush your DNS cache after whitelisting, otherwise your computer won't check Pi-hole again for up to two (or so) days after whitelisting.

However, I have better clarified the error message you should receive in this scenario, in the next upcoming release - hopefully, this will better clarify what is happening.

**Comment by AtomicLight** [comment]
Thanks! 

BTW: Will your add-on automatically update or do I need to re-install?

**Comment by WaLLy3K** [comment]
No worries :)

At the moment, there's no automatic update feature - I need to consider it for a future release. At the moment, you just need to do the installation commands again (which isn't great if you've configured `phbp.ini`), so I'm looking to try and tackle this after the next release.

When an update is available, there's just a little notification in the footer that says "Update Available".

Hopefully everything is sorted - but if not, you're welcome to reopen this!
