### ISSUE TITLE
Docker uses nginx

### ISSUE THREAD

**Issue by kylerw** [WaLLy3K/Pi-hole-Block-Page#5]
Have you worked with the Docker container which is using nginx? Any guidance on install for that scenario? Looks like I need to define the correct path to the .conf or html and that should be it?

**Comment by WaLLy3K** [comment]
I can't say I have worked with Docker, but I feel there's only one thing you'd need to consider for it to work with Nginx:

Pi-hole uses the Lighttpd variable [`server.error-handler-404`](https://redmine.lighttpd.net/projects/1/wiki/Server_error-handler-404Details) to make the block page work. Since you can't directly override that variable without Lighttpd failing to start (and I won't modify `/etc/lighttpd/lighttpd.conf` to achieve this), I use [`url.rewrite-once = ( "pihole/index.php" => "/index.php" )`](https://redmine.lighttpd.net/projects/1/wiki/docs_modrewrite) instead.

If you know of a way to replicate either of these with the Nginx config, then you're golden.

Hope this helps!
